// Code generated by "stringer -type=AuditLogEvent -trimprefix=AuditLogEvent -output audit_log_string.go"; DO NOT EDIT.

package objects

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AuditLogEvtGuildUpdate-1]
	_ = x[AuditLogEventChannelCreate-10]
	_ = x[AuditLogEventChannelUpdate-11]
	_ = x[AuditLogEventChannelDelete-12]
	_ = x[AuditLogEventOverwriteCreate-13]
	_ = x[AuditLogEventOverwriteUpdate-14]
	_ = x[AuditLogEventOverwriteDelete-15]
	_ = x[AuditLogEventMemberKick-20]
	_ = x[AuditLogEventMemberPrune-21]
	_ = x[AuditLogEventMemberBanAdd-22]
	_ = x[AuditLogEventMemberBanRemove-23]
	_ = x[AuditLogEventMemberUpdate-24]
	_ = x[AuditLogEventMemberRoleUpdate-25]
	_ = x[AuditLogEventMemberMove-26]
	_ = x[AuditLogEventMemberDisconnect-27]
	_ = x[AuditLogEventBotAdd-28]
	_ = x[AuditLogEventRoleCreate-30]
	_ = x[AuditLogEventRoleUpdate-31]
	_ = x[AuditLogEventRoleDelete-32]
	_ = x[AuditLogEventInviteCreate-40]
	_ = x[AuditLogEventInviteUpdate-41]
	_ = x[AuditLogEventInviteDelete-42]
	_ = x[AuditLogEventWebhookCreate-50]
	_ = x[AuditLogEventWebhookUpdate-51]
	_ = x[AuditLogEventWebhookDelete-52]
	_ = x[AuditLogEventEmojiCreate-60]
	_ = x[AuditLogEventEmojiUpdate-61]
	_ = x[AuditLogEventEmojiDelete-62]
	_ = x[AuditLogEventMessageDelete-72]
	_ = x[AuditLogEventMessageBulkDelete-73]
	_ = x[AuditLogEventMessagePin-74]
	_ = x[AuditLogEventMessageUnpin-75]
	_ = x[AuditLogEventIntegrationCreate-80]
	_ = x[AuditLogEventIntegrationUpdate-81]
	_ = x[AuditLogEventIntegrationDelete-82]
}

const (
	_AuditLogEvent_name_0 = "AuditLogEvtGuildUpdate"
	_AuditLogEvent_name_1 = "ChannelCreateChannelUpdateChannelDeleteOverwriteCreateOverwriteUpdateOverwriteDelete"
	_AuditLogEvent_name_2 = "MemberKickMemberPruneMemberBanAddMemberBanRemoveMemberUpdateMemberRoleUpdateMemberMoveMemberDisconnectBotAdd"
	_AuditLogEvent_name_3 = "RoleCreateRoleUpdateRoleDelete"
	_AuditLogEvent_name_4 = "InviteCreateInviteUpdateInviteDelete"
	_AuditLogEvent_name_5 = "WebhookCreateWebhookUpdateWebhookDelete"
	_AuditLogEvent_name_6 = "EmojiCreateEmojiUpdateEmojiDelete"
	_AuditLogEvent_name_7 = "MessageDeleteMessageBulkDeleteMessagePinMessageUnpin"
	_AuditLogEvent_name_8 = "IntegrationCreateIntegrationUpdateIntegrationDelete"
)

var (
	_AuditLogEvent_index_1 = [...]uint8{0, 13, 26, 39, 54, 69, 84}
	_AuditLogEvent_index_2 = [...]uint8{0, 10, 21, 33, 48, 60, 76, 86, 102, 108}
	_AuditLogEvent_index_3 = [...]uint8{0, 10, 20, 30}
	_AuditLogEvent_index_4 = [...]uint8{0, 12, 24, 36}
	_AuditLogEvent_index_5 = [...]uint8{0, 13, 26, 39}
	_AuditLogEvent_index_6 = [...]uint8{0, 11, 22, 33}
	_AuditLogEvent_index_7 = [...]uint8{0, 13, 30, 40, 52}
	_AuditLogEvent_index_8 = [...]uint8{0, 17, 34, 51}
)

func (i AuditLogEvent) String() string {
	switch {
	case i == 1:
		return _AuditLogEvent_name_0
	case 10 <= i && i <= 15:
		i -= 10
		return _AuditLogEvent_name_1[_AuditLogEvent_index_1[i]:_AuditLogEvent_index_1[i+1]]
	case 20 <= i && i <= 28:
		i -= 20
		return _AuditLogEvent_name_2[_AuditLogEvent_index_2[i]:_AuditLogEvent_index_2[i+1]]
	case 30 <= i && i <= 32:
		i -= 30
		return _AuditLogEvent_name_3[_AuditLogEvent_index_3[i]:_AuditLogEvent_index_3[i+1]]
	case 40 <= i && i <= 42:
		i -= 40
		return _AuditLogEvent_name_4[_AuditLogEvent_index_4[i]:_AuditLogEvent_index_4[i+1]]
	case 50 <= i && i <= 52:
		i -= 50
		return _AuditLogEvent_name_5[_AuditLogEvent_index_5[i]:_AuditLogEvent_index_5[i+1]]
	case 60 <= i && i <= 62:
		i -= 60
		return _AuditLogEvent_name_6[_AuditLogEvent_index_6[i]:_AuditLogEvent_index_6[i+1]]
	case 72 <= i && i <= 75:
		i -= 72
		return _AuditLogEvent_name_7[_AuditLogEvent_index_7[i]:_AuditLogEvent_index_7[i+1]]
	case 80 <= i && i <= 82:
		i -= 80
		return _AuditLogEvent_name_8[_AuditLogEvent_index_8[i]:_AuditLogEvent_index_8[i+1]]
	default:
		return "AuditLogEvent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
