// +build ignore

package main

import (
	"bytes"
	"io/ioutil"
	"strings"
	"text/template"
)

const start = `// Code generated by generate_command_builder.go; DO NOT EDIT.

package router

//go:generate go run generate_command_builder.go

import "github.com/Postcord/objects"

`

const builderShared = `type {{ .Struct }} struct {
	*commandBuilder
}{{ if .AddOptions }}

func (c {{ .Struct }}) StringOption(name, description string, required bool, choices []StringChoice) {{ .BuilderType }}Builder {
	c.commandBuilder.StringOption(name, description, required, choices)
	return c
}

func (c {{ .Struct }}) IntOption(name, description string, required bool, choices []IntChoice) {{ .BuilderType }}Builder {
	c.commandBuilder.IntOption(name, description, required, choices)
	return c
}

func (c {{ .Struct }}) BoolOption(name, description string, required, default_ bool) {{ .BuilderType }}Builder {
	c.commandBuilder.BoolOption(name, description, required, default_)
	return c
}

func (c {{ .Struct }}) UserOption(name, description string, required bool) {{ .BuilderType }}Builder {
	c.commandBuilder.UserOption(name, description, required)
	return c
}

func (c {{ .Struct }}) ChannelOption(name, description string, required bool) {{ .BuilderType }}Builder {
	c.commandBuilder.ChannelOption(name, description, required)
	return c
}

func (c {{ .Struct }}) RoleOption(name, description string, required bool) {{ .BuilderType }}Builder {
	c.commandBuilder.RoleOption(name, description, required)
	return c
}

func (c {{ .Struct }}) MentionableOption(name, description string, required bool) {{ .BuilderType }}Builder {
	c.commandBuilder.MentionableOption(name, description, required)
	return c
}

func (c {{ .Struct }}) DoubleOption(name, description string, required bool, choices []DoubleChoice) {{ .BuilderType }}Builder {
	c.commandBuilder.DoubleOption(name, description, required, choices)
	return c
}{{ end }}

func (c {{ .Struct }}) DefaultPermission() {{ .BuilderType }}Builder {
	c.commandBuilder.DefaultPermission()
	return c
}

func (c {{ .Struct }}) AllowedMentions(config *objects.AllowedMentions) {{ .BuilderType }}Builder {
	c.commandBuilder.AllowedMentions(config)
	return c
}{{ if not .DoNotHook }}

func (c *commandBuilder) {{ .BuilderType }}() {{ .BuilderType }}Builder {
	c.cmd.commandType = int({{ .CommandType }})
	return {{ .Struct }}{c}
}{{ end }}`

const optionInterface = `type {{ .OutputInterface }} interface {
	// StringOption is used to define an option of the type string. Note that choices is ignored if it's nil or length 0.
	// Maps to option type 3 (STRING): https://discord.com/developers/docs/interactions/slash-commands#application-command-object-application-command-option-type
	StringOption(name, description string, required bool, choices []StringChoice) {{ .InterfaceName }}

	// IntOption is used to define an option of the type int. Note that choices is ignored if it's nil or length 0.
	// Maps to option type 4 (INTEGER): https://discord.com/developers/docs/interactions/slash-commands#application-command-object-application-command-option-type
	IntOption(name, description string, required bool, choices []IntChoice) {{ .InterfaceName }}

	// IntOption is used to define an option of the type bool.
	// Maps to option type 5 (BOOLEAN): https://discord.com/developers/docs/interactions/slash-commands#application-command-object-application-command-option-type
	BoolOption(name, description string, required, default_ bool) {{ .InterfaceName }}

	// IntOption is used to define an option of the type user.
	// Maps to option type 6 (USER): https://discord.com/developers/docs/interactions/slash-commands#application-command-object-application-command-option-type
	UserOption(name, description string, required bool) {{ .InterfaceName }}

	// ChannelOption is used to define an option of the type channel.
	// Maps to option type 7 (CHANNEL): https://discord.com/developers/docs/interactions/slash-commands#application-command-object-application-command-option-type
	ChannelOption(name, description string, required bool) {{ .InterfaceName }}

	// RoleOption is used to define an option of the type role.
	// Maps to option type 8 (ROLE): https://discord.com/developers/docs/interactions/slash-commands#application-command-object-application-command-option-type
	RoleOption(name, description string, required bool) {{ .InterfaceName }}

	// MentionableOption is used to define an option of the type mentionable.
	// Maps to option type 9 (MENTIONABLE): https://discord.com/developers/docs/interactions/slash-commands#application-command-object-application-command-option-type
	MentionableOption(name, description string, required bool) {{ .InterfaceName }}

	// DoubleOption is used to define an option of the type double. Note that choices is ignored if it's nil or length 0.
	// Maps to option type 10 (INTEGER): https://discord.com/developers/docs/interactions/slash-commands#application-command-object-application-command-option-type
	DoubleOption(name, description string, required bool, choices []DoubleChoice) {{ .InterfaceName }}
}`

var builderTypes = []struct{
	Struct      string
	BuilderType string
	CommandType string
	DoNotHook   bool
	AddOptions  bool
}{
	{
		Struct:      "textCommandBuilder",
		BuilderType: "TextCommand",
		CommandType: "objects.CommandTypeChatInput",
		AddOptions:  true,
	},
	{
		Struct:      "subcommandBuilder",
		BuilderType: "SubCommand",
		CommandType: "objects.CommandTypeChatInput",
		DoNotHook:   true,
		AddOptions:  true,
	},
	{
		Struct:      "messageCommandBuilder",
		BuilderType: "MessageCommand",
		CommandType: "objects.CommandTypeMessage",
	},
	{
		Struct:      "userCommandBuilder",
		BuilderType: "UserCommand",
		CommandType: "objects.CommandTypeUser",
	},
}

var interfaceTypes = []struct{
	InterfaceName   string
	OutputInterface string
}{
	{InterfaceName: "CommandBuilder", OutputInterface: "commandOptions"},
	{InterfaceName: "SubCommandBuilder", OutputInterface: "subCommandOptions"},
	{InterfaceName: "TextCommandBuilder", OutputInterface: "textCommandOptions"},
}

func main() {
	file := start
	parts := make([]string, len(builderTypes)+len(interfaceTypes))
	t, err := template.New("_").Parse(builderShared)
	if err != nil {
		panic(err)
	}
	for i, v := range builderTypes {
		buf := &bytes.Buffer{}
		if err := t.Execute(buf, v); err != nil {
			panic(err)
		}
		parts[i] = buf.String()
	}
	t, err = template.New("_").Parse(optionInterface)
	if err != nil {
		panic(err)
	}
	for i, v := range interfaceTypes {
		buf := &bytes.Buffer{}
		if err := t.Execute(buf, v); err != nil {
			panic(err)
		}
		parts[i+len(builderTypes)] = buf.String()
	}
	file += strings.Join(parts, "\n\n") + "\n"
	if err := ioutil.WriteFile("command_builder_gen.go", []byte(file), 0666); err != nil {
		panic(err)
	}
}
