// Code generated by "stringer -type=GuildScheduledEventStatus,GuildScheduledEventEntityType -output guild_scheduled_event_string.go"; DO NOT EDIT.

package objects

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventStatusScheduled-1]
	_ = x[EventStatusActive-2]
	_ = x[EventStatusCompleted-3]
	_ = x[EventStatusCanceled-4]
}

const _GuildScheduledEventStatus_name = "EventStatusScheduledEventStatusActiveEventStatusCompletedEventStatusCanceled"

var _GuildScheduledEventStatus_index = [...]uint8{0, 20, 37, 57, 76}

func (i GuildScheduledEventStatus) String() string {
	i -= 1
	if i < 0 || i >= GuildScheduledEventStatus(len(_GuildScheduledEventStatus_index)-1) {
		return "GuildScheduledEventStatus(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _GuildScheduledEventStatus_name[_GuildScheduledEventStatus_index[i]:_GuildScheduledEventStatus_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EntityTypeStageInstance-1]
	_ = x[EntityTypeVoice-2]
	_ = x[EntityTypeExternal-3]
}

const _GuildScheduledEventEntityType_name = "EntityTypeStageInstanceEntityTypeVoiceEntityTypeExternal"

var _GuildScheduledEventEntityType_index = [...]uint8{0, 23, 38, 56}

func (i GuildScheduledEventEntityType) String() string {
	i -= 1
	if i < 0 || i >= GuildScheduledEventEntityType(len(_GuildScheduledEventEntityType_index)-1) {
		return "GuildScheduledEventEntityType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _GuildScheduledEventEntityType_name[_GuildScheduledEventEntityType_index[i]:_GuildScheduledEventEntityType_index[i+1]]
}
