// Code generated by "stringer -type=ExpireBehavior -trimprefix=ExpireBehavior -output integration_string.go"; DO NOT EDIT.

package objects

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExpireBehaviorRemoveRole-0]
	_ = x[ExpireBehaviorKick-1]
}

const _ExpireBehavior_name = "RemoveRoleKick"

var _ExpireBehavior_index = [...]uint8{0, 10, 14}

func (i ExpireBehavior) String() string {
	if i >= ExpireBehavior(len(_ExpireBehavior_index)-1) {
		return "ExpireBehavior(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExpireBehavior_name[_ExpireBehavior_index[i]:_ExpireBehavior_index[i+1]]
}
