// Code generated by "stringer -type=InviteTargetType -trimprefix=InviteTargetType -output invite_string.go"; DO NOT EDIT.

package objects

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InviteTargetTypeStream-1]
	_ = x[InviteTargetTypeEmbeddedApplication-2]
}

const _InviteTargetType_name = "StreamEmbeddedApplication"

var _InviteTargetType_index = [...]uint8{0, 6, 25}

func (i InviteTargetType) String() string {
	i -= 1
	if i < 0 || i >= InviteTargetType(len(_InviteTargetType_index)-1) {
		return "InviteTargetType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _InviteTargetType_name[_InviteTargetType_index[i]:_InviteTargetType_index[i+1]]
}
