// Code generated by "stringer -type=MessageType,MessageActivityType,MessageFlag,MessageStickerFormat -output message_string.go"; DO NOT EDIT.

package objects

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MessageTypeDefault-0]
	_ = x[MessageTypeRecipientAdd-1]
	_ = x[MessageTypeRecipientRemove-2]
	_ = x[MessageTypeCall-3]
	_ = x[MessageTypeChannelNameChange-4]
	_ = x[MessageTypeChannelIconChange-5]
	_ = x[MessageTypeChannelPinnedMessage-6]
	_ = x[MessageTypeGuildMemberJoin-7]
	_ = x[MessageTypeUserPremiumGuildSubscription-8]
	_ = x[MessageTypeUserPremiumGuildSubscriptionTier1-9]
	_ = x[MessageTypeUserPremiumGuildSubscriptionTier2-10]
	_ = x[MessageTypeUserPremiumGuildSubscriptionTier3-11]
	_ = x[MessageTypeChannelFollowAdd-12]
	_ = x[MessageTypeGuildDiscoveryDisqualified-14]
	_ = x[MessageTypeGuildDiscoveryRequalified-15]
	_ = x[MessageTypeGuildDiscoveryGracePeriodInitialWarning-16]
	_ = x[MessageTypeGuildDiscoveryGracePeriodFinalWarning-17]
	_ = x[MessageTypeReply-19]
	_ = x[MessageTypeApplicationCommand-20]
}

const (
	_MessageType_name_0 = "MessageTypeDefaultMessageTypeRecipientAddMessageTypeRecipientRemoveMessageTypeCallMessageTypeChannelNameChangeMessageTypeChannelIconChangeMessageTypeChannelPinnedMessageMessageTypeGuildMemberJoinMessageTypeUserPremiumGuildSubscriptionMessageTypeUserPremiumGuildSubscriptionTier1MessageTypeUserPremiumGuildSubscriptionTier2MessageTypeUserPremiumGuildSubscriptionTier3MessageTypeChannelFollowAdd"
	_MessageType_name_1 = "MessageTypeGuildDiscoveryDisqualifiedMessageTypeGuildDiscoveryRequalifiedMessageTypeGuildDiscoveryGracePeriodInitialWarningMessageTypeGuildDiscoveryGracePeriodFinalWarning"
	_MessageType_name_2 = "MessageTypeReplyMessageTypeApplicationCommand"
)

var (
	_MessageType_index_0 = [...]uint16{0, 18, 41, 67, 82, 110, 138, 169, 195, 234, 278, 322, 366, 393}
	_MessageType_index_1 = [...]uint8{0, 37, 73, 123, 171}
	_MessageType_index_2 = [...]uint8{0, 16, 45}
)

func (i MessageType) String() string {
	switch {
	case i <= 12:
		return _MessageType_name_0[_MessageType_index_0[i]:_MessageType_index_0[i+1]]
	case 14 <= i && i <= 17:
		i -= 14
		return _MessageType_name_1[_MessageType_index_1[i]:_MessageType_index_1[i+1]]
	case 19 <= i && i <= 20:
		i -= 19
		return _MessageType_name_2[_MessageType_index_2[i]:_MessageType_index_2[i+1]]
	default:
		return "MessageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MessageActivityTypeJoin-1]
	_ = x[MessageActivityTypeSpectate-2]
	_ = x[MessageActivityTypeListen-3]
	_ = x[MessageActivityTypeJoinRequest-5]
}

const (
	_MessageActivityType_name_0 = "MessageActivityTypeJoinMessageActivityTypeSpectateMessageActivityTypeListen"
	_MessageActivityType_name_1 = "MessageActivityTypeJoinRequest"
)

var (
	_MessageActivityType_index_0 = [...]uint8{0, 23, 50, 75}
)

func (i MessageActivityType) String() string {
	switch {
	case 1 <= i && i <= 3:
		i -= 1
		return _MessageActivityType_name_0[_MessageActivityType_index_0[i]:_MessageActivityType_index_0[i+1]]
	case i == 5:
		return _MessageActivityType_name_1
	default:
		return "MessageActivityType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MsgFlagCrossposted-1]
	_ = x[MsgFlagIsCrosspost-2]
	_ = x[MsgFlagSupressEmbeds-4]
	_ = x[MsgFlagSourceMessageDeleted-8]
	_ = x[MsgFlagUrgent-16]
	_ = x[MsgFlagEphemeral-64]
	_ = x[MsgFlagLoading-128]
}

const (
	_MessageFlag_name_0 = "MsgFlagCrosspostedMsgFlagIsCrosspost"
	_MessageFlag_name_1 = "MsgFlagSupressEmbeds"
	_MessageFlag_name_2 = "MsgFlagSourceMessageDeleted"
	_MessageFlag_name_3 = "MsgFlagUrgent"
	_MessageFlag_name_4 = "MsgFlagEphemeral"
	_MessageFlag_name_5 = "MsgFlagLoading"
)

var (
	_MessageFlag_index_0 = [...]uint8{0, 18, 36}
)

func (i MessageFlag) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _MessageFlag_name_0[_MessageFlag_index_0[i]:_MessageFlag_index_0[i+1]]
	case i == 4:
		return _MessageFlag_name_1
	case i == 8:
		return _MessageFlag_name_2
	case i == 16:
		return _MessageFlag_name_3
	case i == 64:
		return _MessageFlag_name_4
	case i == 128:
		return _MessageFlag_name_5
	default:
		return "MessageFlag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PNGStickerFormat-1]
	_ = x[APNGStickerFormat-2]
	_ = x[LottieStickerFormat-3]
}

const _MessageStickerFormat_name = "PNGStickerFormatAPNGStickerFormatLottieStickerFormat"

var _MessageStickerFormat_index = [...]uint8{0, 16, 33, 52}

func (i MessageStickerFormat) String() string {
	i -= 1
	if i >= MessageStickerFormat(len(_MessageStickerFormat_index)-1) {
		return "MessageStickerFormat(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _MessageStickerFormat_name[_MessageStickerFormat_index[i]:_MessageStickerFormat_index[i+1]]
}
