// Code generated by "stringer -type UserFlags,PremiumType,ActivityType,ActivityFlag -output user_string.go"; DO NOT EDIT.

package objects

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UserFlagsNone-0]
	_ = x[DiscordEmployee-1]
	_ = x[PartneredServerOwner-2]
	_ = x[HypesquadEvents-4]
	_ = x[BugHunterLevel1-8]
	_ = x[HouseBravery-16]
	_ = x[HouseBrilliance-32]
	_ = x[HouseBalance-64]
	_ = x[EarlySupporter-128]
	_ = x[TeamUser-256]
	_ = x[System-4096]
	_ = x[BugHunterLevel2-16384]
	_ = x[VerifiedBot-65536]
	_ = x[EarlyVerifiedBotDeveloper-131072]
}

const _UserFlags_name = "UserFlagsNoneDiscordEmployeePartneredServerOwnerHypesquadEventsBugHunterLevel1HouseBraveryHouseBrillianceHouseBalanceEarlySupporterTeamUserSystemBugHunterLevel2VerifiedBotEarlyVerifiedBotDeveloper"

var _UserFlags_map = map[UserFlags]string{
	0:      _UserFlags_name[0:13],
	1:      _UserFlags_name[13:28],
	2:      _UserFlags_name[28:48],
	4:      _UserFlags_name[48:63],
	8:      _UserFlags_name[63:78],
	16:     _UserFlags_name[78:90],
	32:     _UserFlags_name[90:105],
	64:     _UserFlags_name[105:117],
	128:    _UserFlags_name[117:131],
	256:    _UserFlags_name[131:139],
	4096:   _UserFlags_name[139:145],
	16384:  _UserFlags_name[145:160],
	65536:  _UserFlags_name[160:171],
	131072: _UserFlags_name[171:196],
}

func (i UserFlags) String() string {
	if str, ok := _UserFlags_map[i]; ok {
		return str
	}
	return "UserFlags(" + strconv.FormatInt(int64(i), 10) + ")"
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PremiumTypeNone-0]
	_ = x[NitroClassic-1]
	_ = x[Nitro-2]
}

const _PremiumType_name = "PremiumTypeNoneNitroClassicNitro"

var _PremiumType_index = [...]uint8{0, 15, 27, 32}

func (i PremiumType) String() string {
	if i >= PremiumType(len(_PremiumType_index)-1) {
		return "PremiumType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PremiumType_name[_PremiumType_index[i]:_PremiumType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Game-0]
	_ = x[Streaming-1]
	_ = x[Listening-2]
	_ = x[Custom-3]
	_ = x[Competing-4]
}

const _ActivityType_name = "GameStreamingListeningCustomCompeting"

var _ActivityType_index = [...]uint8{0, 4, 13, 22, 28, 37}

func (i ActivityType) String() string {
	if i >= ActivityType(len(_ActivityType_index)-1) {
		return "ActivityType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ActivityType_name[_ActivityType_index[i]:_ActivityType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ActivityInstance-1]
	_ = x[ActivityJoin-2]
	_ = x[ActivitySpectate-4]
	_ = x[ActivityJoinRequest-8]
	_ = x[ActivitySync-16]
	_ = x[ActivityPlay-32]
}

const (
	_ActivityFlag_name_0 = "ActivityInstanceActivityJoin"
	_ActivityFlag_name_1 = "ActivitySpectate"
	_ActivityFlag_name_2 = "ActivityJoinRequest"
	_ActivityFlag_name_3 = "ActivitySync"
	_ActivityFlag_name_4 = "ActivityPlay"
)

var (
	_ActivityFlag_index_0 = [...]uint8{0, 16, 28}
)

func (i ActivityFlag) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _ActivityFlag_name_0[_ActivityFlag_index_0[i]:_ActivityFlag_index_0[i+1]]
	case i == 4:
		return _ActivityFlag_name_1
	case i == 8:
		return _ActivityFlag_name_2
	case i == 16:
		return _ActivityFlag_name_3
	case i == 32:
		return _ActivityFlag_name_4
	default:
		return "ActivityFlag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
