// Code generated by "stringer -type=WebhookType -output webhook_string.go"; DO NOT EDIT.

package objects

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IncomingWebhook-1]
	_ = x[ChannelFollowWebhook-2]
}

const _WebhookType_name = "IncomingWebhookChannelFollowWebhook"

var _WebhookType_index = [...]uint8{0, 15, 35}

func (i WebhookType) String() string {
	i -= 1
	if i >= WebhookType(len(_WebhookType_index)-1) {
		return "WebhookType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _WebhookType_name[_WebhookType_index[i]:_WebhookType_index[i+1]]
}
