// Code generated by "stringer -type=ApplicationFlag,TeamMembershipState -output application_string.go"; DO NOT EDIT.

package objects

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ApplicationFlagGatewayPresence-4096]
	_ = x[ApplicationFlagGatewayPresenceLimited-8192]
	_ = x[ApplicationFlagGatewayGuildMembers-16384]
	_ = x[ApplicationFlagGatewayGuildMembersLimited-32768]
	_ = x[ApplicationFlagVerificationPendingGuildLimit-65536]
	_ = x[ApplicationFlagEmbedded-131072]
	_ = x[ApplicationFlagMessageContent-262144]
	_ = x[ApplicationFlagMessageContentLimited-524288]
}

const (
	_ApplicationFlag_name_0 = "ApplicationFlagGatewayPresence"
	_ApplicationFlag_name_1 = "ApplicationFlagGatewayPresenceLimited"
	_ApplicationFlag_name_2 = "ApplicationFlagGatewayGuildMembers"
	_ApplicationFlag_name_3 = "ApplicationFlagGatewayGuildMembersLimited"
	_ApplicationFlag_name_4 = "ApplicationFlagVerificationPendingGuildLimit"
	_ApplicationFlag_name_5 = "ApplicationFlagEmbedded"
	_ApplicationFlag_name_6 = "ApplicationFlagMessageContent"
	_ApplicationFlag_name_7 = "ApplicationFlagMessageContentLimited"
)

func (i ApplicationFlag) String() string {
	switch {
	case i == 4096:
		return _ApplicationFlag_name_0
	case i == 8192:
		return _ApplicationFlag_name_1
	case i == 16384:
		return _ApplicationFlag_name_2
	case i == 32768:
		return _ApplicationFlag_name_3
	case i == 65536:
		return _ApplicationFlag_name_4
	case i == 131072:
		return _ApplicationFlag_name_5
	case i == 262144:
		return _ApplicationFlag_name_6
	case i == 524288:
		return _ApplicationFlag_name_7
	default:
		return "ApplicationFlag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TeamMembershipStateInvited-1]
	_ = x[TeamMembershipStateAccepted-2]
}

const _TeamMembershipState_name = "TeamMembershipStateInvitedTeamMembershipStateAccepted"

var _TeamMembershipState_index = [...]uint8{0, 26, 53}

func (i TeamMembershipState) String() string {
	i -= 1
	if i < 0 || i >= TeamMembershipState(len(_TeamMembershipState_index)-1) {
		return "TeamMembershipState(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _TeamMembershipState_name[_TeamMembershipState_index[i]:_TeamMembershipState_index[i+1]]
}
