// Code generated by "stringer -type=AutoModerationEventType,AutoModerationTriggerType,AutoModerationKeywordPresetType,AutoModerationActionType -trimprefix=AutoModeration -output auto_moderation_string.go"; DO NOT EDIT.

package objects

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AutoModerationEventTypeMessageSend-1]
}

const _AutoModerationEventType_name = "EventTypeMessageSend"

var _AutoModerationEventType_index = [...]uint8{0, 20}

func (i AutoModerationEventType) String() string {
	i -= 1
	if i >= AutoModerationEventType(len(_AutoModerationEventType_index)-1) {
		return "AutoModerationEventType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _AutoModerationEventType_name[_AutoModerationEventType_index[i]:_AutoModerationEventType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AutoModerationTriggerTypeKeyword-1]
	_ = x[AutoModerationTriggerTypeSpam-2]
	_ = x[AutoModerationTriggerTypeKeywordPreset-3]
	_ = x[AutoModerationTriggerTypeMentionSpam-4]
}

const _AutoModerationTriggerType_name = "TriggerTypeKeywordTriggerTypeSpamTriggerTypeKeywordPresetTriggerTypeMentionSpam"

var _AutoModerationTriggerType_index = [...]uint8{0, 18, 33, 57, 79}

func (i AutoModerationTriggerType) String() string {
	i -= 1
	if i >= AutoModerationTriggerType(len(_AutoModerationTriggerType_index)-1) {
		return "AutoModerationTriggerType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _AutoModerationTriggerType_name[_AutoModerationTriggerType_index[i]:_AutoModerationTriggerType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AutoModerationKeywordPresetTypeProfanity-1]
	_ = x[AutoModerationKeywordPresetTypeSexualContent-2]
	_ = x[AutoModerationKeywordPresetTypeSlurs-3]
}

const _AutoModerationKeywordPresetType_name = "KeywordPresetTypeProfanityKeywordPresetTypeSexualContentKeywordPresetTypeSlurs"

var _AutoModerationKeywordPresetType_index = [...]uint8{0, 26, 56, 78}

func (i AutoModerationKeywordPresetType) String() string {
	i -= 1
	if i >= AutoModerationKeywordPresetType(len(_AutoModerationKeywordPresetType_index)-1) {
		return "AutoModerationKeywordPresetType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _AutoModerationKeywordPresetType_name[_AutoModerationKeywordPresetType_index[i]:_AutoModerationKeywordPresetType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AutoModerationActionTypeBlockMessage-1]
	_ = x[AutoModerationActionTypeSendAlertMessage-2]
	_ = x[AutoModerationActionTypeTimeout-3]
}

const _AutoModerationActionType_name = "ActionTypeBlockMessageActionTypeSendAlertMessageActionTypeTimeout"

var _AutoModerationActionType_index = [...]uint8{0, 22, 48, 65}

func (i AutoModerationActionType) String() string {
	i -= 1
	if i >= AutoModerationActionType(len(_AutoModerationActionType_index)-1) {
		return "AutoModerationActionType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _AutoModerationActionType_name[_AutoModerationActionType_index[i]:_AutoModerationActionType_index[i+1]]
}
