// Code generated by "stringer -type=ChannelType -trimprefix=ChannelType -output channel_string.go"; DO NOT EDIT.

package objects

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ChannelTypeGuildText-0]
	_ = x[ChannelTypeDM-1]
	_ = x[ChannelTypeGuildVoice-2]
	_ = x[ChannelTypeGroupDM-3]
	_ = x[ChannelTypeGuildCategory-4]
	_ = x[ChannelTypeGuildNews-5]
	_ = x[ChannelTypeGuildStore-6]
}

const _ChannelType_name = "GuildTextDMGuildVoiceGroupDMGuildCategoryGuildNewsGuildStore"

var _ChannelType_index = [...]uint8{0, 9, 11, 21, 28, 41, 50, 60}

func (i ChannelType) String() string {
	if i >= ChannelType(len(_ChannelType_index)-1) {
		return "ChannelType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ChannelType_name[_ChannelType_index[i]:_ChannelType_index[i+1]]
}
