package objects

//go:generate stringer -type=JSONErrorCode -linecomment -output errors_string.go

type JSONErrorCode uint

const (
	JSONErrorGeneralError                                                     JSONErrorCode = 0      // General error (such as a malformed request body, amongst other things)
	JSONErrorUnknownAccount                                                   JSONErrorCode = 10001  // Unknown account
	JSONErrorUnknownApplication                                               JSONErrorCode = 10002  // Unknown application
	JSONErrorUnknownChannel                                                   JSONErrorCode = 10003  // Unknown channel
	JSONErrorUnknownGuild                                                     JSONErrorCode = 10004  // Unknown guild
	JSONErrorUnknownIntegration                                               JSONErrorCode = 10005  // Unknown integration
	JSONErrorUnknownInvite                                                    JSONErrorCode = 10006  // Unknown invite
	JSONErrorUnknownMember                                                    JSONErrorCode = 10007  // Unknown member
	JSONErrorUnknownMessage                                                   JSONErrorCode = 10008  // Unknown message
	JSONErrorUnknownPermissionOverwrite                                       JSONErrorCode = 10009  // Unknown permission overwrite
	JSONErrorUnknownProvider                                                  JSONErrorCode = 10010  // Unknown provider
	JSONErrorUnknownRole                                                      JSONErrorCode = 10011  // Unknown role
	JSONErrorUnknownToken                                                     JSONErrorCode = 10012  // Unknown token
	JSONErrorUnknownUser                                                      JSONErrorCode = 10013  // Unknown user
	JSONErrorUnknownEmoji                                                     JSONErrorCode = 10014  // Unknown emoji
	JSONErrorUnknownWebhook                                                   JSONErrorCode = 10015  // Unknown webhook
	JSONErrorUnknownWebhookService                                            JSONErrorCode = 10016  // Unknown webhook service
	JSONErrorUnknownSession                                                   JSONErrorCode = 10020  // Unknown session
	JSONErrorUnknownBan                                                       JSONErrorCode = 10026  // Unknown ban
	JSONErrorUnknownSKU                                                       JSONErrorCode = 10027  // Unknown SKU
	JSONErrorUnknownStoreListing                                              JSONErrorCode = 10028  // Unknown Store Listing
	JSONErrorUnknownEntitlement                                               JSONErrorCode = 10029  // Unknown entitlement
	JSONErrorUnknownBuild                                                     JSONErrorCode = 10030  // Unknown build
	JSONErrorUnknownLobby                                                     JSONErrorCode = 10031  // Unknown lobby
	JSONErrorUnknownBranch                                                    JSONErrorCode = 10032  // Unknown branch
	JSONErrorUnknownStoreDirectoryLayout                                      JSONErrorCode = 10033  // Unknown store directory layout
	JSONErrorUnknownRedistributable                                           JSONErrorCode = 10036  // Unknown redistributable
	JSONErrorUnknownGiftCode                                                  JSONErrorCode = 10038  // Unknown gift code
	JSONErrorUnknownStream                                                    JSONErrorCode = 10049  // Unknown stream
	JSONErrorUnknownPremiumServerSubscribeCooldown                            JSONErrorCode = 10050  // Unknown premium server subscribe cooldown
	JSONErrorUnknownGuildTemplate                                             JSONErrorCode = 10057  // Unknown guild template
	JSONErrorUnknownDiscoverableServerCategory                                JSONErrorCode = 10059  // Unknown discoverable server category
	JSONErrorUnknownSticker                                                   JSONErrorCode = 10060  // Unknown sticker
	JSONErrorUnknownInteraction                                               JSONErrorCode = 10062  // Unknown interaction
	JSONErrorUnknownApplicationCommand                                        JSONErrorCode = 10063  // Unknown application command
	JSONErrorUnknownApplicationCommandPermissions                             JSONErrorCode = 10066  // Unknown application command permissions
	JSONErrorUnknownStageInstance                                             JSONErrorCode = 10067  // Unknown Stage Instance
	JSONErrorUnknownGuildMemberVerificationForm                               JSONErrorCode = 10068  // Unknown Guild Member Verification Form
	JSONErrorUnknownGuildWelcomeScreen                                        JSONErrorCode = 10069  // Unknown Guild Welcome Screen
	JSONErrorUnknownGuildScheduledEvent                                       JSONErrorCode = 10070  // Unknown Guild Scheduled Event
	JSONErrorUnknownGuildScheduledEventUser                                   JSONErrorCode = 10071  // Unknown Guild Scheduled Event User
	JSONErrorBotsCannotUseThisEndpoint                                        JSONErrorCode = 20001  // Bots cannot use this endpoint
	JSONErrorOnlyBotsCanUseThisEndpoint                                       JSONErrorCode = 20002  // Only bots can use this endpoint
	JSONErrorExplicitContentCannotBeSentToTheDesiredRecipient                 JSONErrorCode = 20009  // Explicit content cannot be sent to the desired recipient(s)
	JSONErrorYouAreNotAuthorizedToPerformThisActionOnThisApplication          JSONErrorCode = 20012  // You are not authorized to perform this action on this application
	JSONErrorThisActionCannotBePerformedDueToSlowmodeRateLimit                JSONErrorCode = 20016  // This action cannot be performed due to slowmode rate limit
	JSONErrorOnlyTheOwnerOfThisAccountCanPerformThisAction                    JSONErrorCode = 20018  // Only the owner of this account can perform this action
	JSONErrorThisMessageCannotBeEditedDueToAnnouncementRateLimits             JSONErrorCode = 20022  // This message cannot be edited due to announcement rate limits
	JSONErrorTheChannelYouAreWritingHasHitTheWriteRateLimit                   JSONErrorCode = 20028  // The channel you are writing has hit the write rate limit
	JSONErrorTheWriteActionYouArePerformingOnTheServerHasHitTheWriteRateLimit JSONErrorCode = 20029  // The write action you are performing on the server has hit the write rate limit
	JSONErrorYourStageTopic                                                   JSONErrorCode = 20031  // Your Stage topic, server name, server description, or channel names contain words that are not allowed
	JSONErrorGuildPremiumSubscriptionLevelTooLow                              JSONErrorCode = 20035  // Guild premium subscription level too low
	JSONErrorMaximumNumberOfGuildsReached                                     JSONErrorCode = 30001  // Maximum number of guilds reached (100)
	JSONErrorMaximumNumberOfFriendsReached                                    JSONErrorCode = 30002  // Maximum number of friends reached (1000)
	JSONErrorMaximumNumberOfPinsReachedForTheChannel                          JSONErrorCode = 30003  // Maximum number of pins reached for the channel (50)
	JSONErrorMaximumNumberOfRecipientsReached                                 JSONErrorCode = 30004  // Maximum number of recipients reached (10)
	JSONErrorMaximumNumberOfGuildRolesReached                                 JSONErrorCode = 30005  // Maximum number of guild roles reached (250)
	JSONErrorMaximumNumberOfWebhooksReached                                   JSONErrorCode = 30007  // Maximum number of webhooks reached (10)
	JSONErrorMaximumNumberOfEmojisReached                                     JSONErrorCode = 30008  // Maximum number of emojis reached
	JSONErrorMaximumNumberOfReactionsReached                                  JSONErrorCode = 30010  // Maximum number of reactions reached (20)
	JSONErrorMaximumNumberOfGuildChannelsReached                              JSONErrorCode = 30013  // Maximum number of guild channels reached (500)
	JSONErrorMaximumNumberOfAttachmentsInAMessageReached                      JSONErrorCode = 30015  // Maximum number of attachments in a message reached (10)
	JSONErrorMaximumNumberOfInvitesReached                                    JSONErrorCode = 30016  // Maximum number of invites reached (1000)
	JSONErrorMaximumNumberOfAnimatedEmojisReached                             JSONErrorCode = 30018  // Maximum number of animated emojis reached
	JSONErrorMaximumNumberOfServerMembersReached                              JSONErrorCode = 30019  // Maximum number of server members reached
	JSONErrorMaximumNumberOfServerCategoriesHasBeenReached                    JSONErrorCode = 30030  // Maximum number of server categories has been reached (5)
	JSONErrorGuildAlreadyHasATemplate                                         JSONErrorCode = 30031  // Guild already has a template
	JSONErrorMaxNumberOfThreadParticipantsHasBeenReached                      JSONErrorCode = 30033  // Max number of thread participants has been reached (1000)
	JSONErrorMaximumNumberOfBansForNon                                        JSONErrorCode = 30035  // Maximum number of bans for non-guild members have been exceeded
	JSONErrorMaximumNumberOfBansFetchesHasBeenReached                         JSONErrorCode = 30037  // Maximum number of bans fetches has been reached
	JSONErrorMaximumNumberOfUncompletedGuildScheduledEventsReached            JSONErrorCode = 30038  // Maximum number of uncompleted guild scheduled events reached (100)
	JSONErrorMaximumNumberOfStickersReached                                   JSONErrorCode = 30039  // Maximum number of stickers reached
	JSONErrorMaximumNumberOfPruneRequestsHasBeenReached                       JSONErrorCode = 30040  // Maximum number of prune requests has been reached. Try again later
	JSONErrorMaximumNumberOfGuildWidgetSettingsUpdatesHasBeenReached          JSONErrorCode = 30042  // Maximum number of guild widget settings updates has been reached. Try again later
	JSONErrorMaximumNumberOfEditsToMessagesOlderThan1HourReached              JSONErrorCode = 30046  // Maximum number of edits to messages older than 1 hour reached. Try again later
	JSONErrorUnauthorized                                                     JSONErrorCode = 40001  // Unauthorized. Provide a valid token and try again
	JSONErrorYouNeedToVerifyYourAccountInOrderToPerformThisAction             JSONErrorCode = 40002  // You need to verify your account in order to perform this action
	JSONErrorYouAreOpeningDirectMessagesTooFast                               JSONErrorCode = 40003  // You are opening direct messages too fast
	JSONErrorSendMessagesHasBeenTemporarilyDisabled                           JSONErrorCode = 40004  // Send messages has been temporarily disabled
	JSONErrorRequestEntityTooLarge                                            JSONErrorCode = 40005  // Request entity too large. Try sending something smaller in size
	JSONErrorThisFeatureHasBeenTemporarilyDisabledServer                      JSONErrorCode = 40006  // This feature has been temporarily disabled server-side
	JSONErrorTheUserIsBannedFromThisGuild                                     JSONErrorCode = 40007  // The user is banned from this guild
	JSONErrorTargetUserIsNotConnectedToVoice                                  JSONErrorCode = 40032  // Target user is not connected to voice
	JSONErrorThisMessageHasAlreadyBeenCrossposted                             JSONErrorCode = 40033  // This message has already been crossposted
	JSONErrorAnApplicationCommandWithThatNameAlreadyExists                    JSONErrorCode = 40041  // An application command with that name already exists
	JSONErrorMissingAccess                                                    JSONErrorCode = 50001  // Missing access
	JSONErrorInvalidAccountType                                               JSONErrorCode = 50002  // Invalid account type
	JSONErrorCannotExecuteActionOnADMChannel                                  JSONErrorCode = 50003  // Cannot execute action on a DM channel
	JSONErrorGuildWidgetDisabled                                              JSONErrorCode = 50004  // Guild widget disabled
	JSONErrorCannotEditAMessageAuthoredByAnotherUser                          JSONErrorCode = 50005  // Cannot edit a message authored by another user
	JSONErrorCannotSendAnEmptyMessage                                         JSONErrorCode = 50006  // Cannot send an empty message
	JSONErrorCannotSendMessagesToThisUser                                     JSONErrorCode = 50007  // Cannot send messages to this user
	JSONErrorCannotSendMessagesInAVoiceChannel                                JSONErrorCode = 50008  // Cannot send messages in a voice channel
	JSONErrorChannelVerificationLevelIsTooHighForYouToGainAccess              JSONErrorCode = 50009  // Channel verification level is too high for you to gain access
	JSONErrorOAuth2ApplicationDoesNotHaveABot                                 JSONErrorCode = 50010  // OAuth2 application does not have a bot
	JSONErrorOAuth2ApplicationLimitReached                                    JSONErrorCode = 50011  // OAuth2 application limit reached
	JSONErrorInvalidOAuth2State                                               JSONErrorCode = 50012  // Invalid OAuth2 state
	JSONErrorYouLackPermissionsToPerformThatAction                            JSONErrorCode = 50013  // You lack permissions to perform that action
	JSONErrorInvalidAuthenticationTokenProvided                               JSONErrorCode = 50014  // Invalid authentication token provided
	JSONErrorNoteWasTooLong                                                   JSONErrorCode = 50015  // Note was too long
	JSONErrorProvidedTooFewOrTooManyMessagesToDelete                          JSONErrorCode = 50016  // Provided too few or too many messages to delete. Must provide at least 2 and fewer than 100 messages to delete
	JSONErrorAMessageCanOnlyBePinnedToTheChannelItWasSentIn                   JSONErrorCode = 50019  // A message can only be pinned to the channel it was sent in
	JSONErrorInviteCodeWasEitherInvalidOrTaken                                JSONErrorCode = 50020  // Invite code was either invalid or taken
	JSONErrorCannotExecuteActionOnASystemMessage                              JSONErrorCode = 50021  // Cannot execute action on a system message
	JSONErrorCannotExecuteActionOnThisChannelType                             JSONErrorCode = 50024  // Cannot execute action on this channel type
	JSONErrorInvalidOAuth2AccessTokenProvided                                 JSONErrorCode = 50025  // Invalid OAuth2 access token provided
	JSONErrorMissingRequiredOAuth2Scope                                       JSONErrorCode = 50026  // Missing required OAuth2 scope
	JSONErrorInvalidWebhookTokenProvided                                      JSONErrorCode = 50027  // Invalid webhook token provided
	JSONErrorInvalidRole                                                      JSONErrorCode = 50028  // Invalid role
	JSONErrorInvalidRecipient                                                 JSONErrorCode = 50033  // Invalid Recipient(s)
	JSONErrorAMessageProvidedWasTooOldToBulkDelete                            JSONErrorCode = 50034  // A message provided was too old to bulk delete
	JSONErrorInvalidFormBody                                                  JSONErrorCode = 50035  // Invalid form body (returned for both
	JSONErrorAnInviteWasAcceptedToAGuildTheApplication                        JSONErrorCode = 50036  // An invite was accepted to a guild the application's bot is not in
	JSONErrorInvalidAPIVersionProvided                                        JSONErrorCode = 50041  // Invalid API version provided
	JSONErrorFileUploadedExceedsTheMaximumSize                                JSONErrorCode = 50045  // File uploaded exceeds the maximum size
	JSONErrorInvalidFileUploaded                                              JSONErrorCode = 50046  // Invalid file uploaded
	JSONErrorCannotSelf                                                       JSONErrorCode = 50054  // Cannot self-redeem this gift
	JSONErrorInvalidGuild                                                     JSONErrorCode = 50055  // Invalid Guild
	JSONErrorInvalidMessageType                                               JSONErrorCode = 50068  // Invalid message type
	JSONErrorPaymentSourceRequiredToRedeemGift                                JSONErrorCode = 50070  // Payment source required to redeem gift
	JSONErrorCannotDeleteAChannelRequiredForCommunityGuilds                   JSONErrorCode = 50074  // Cannot delete a channel required for Community guilds
	JSONErrorInvalidStickerSent                                               JSONErrorCode = 50081  // Invalid sticker sent
	JSONErrorTriedToPerformAnOperationOnAnArchivedThread                      JSONErrorCode = 50083  // Tried to perform an operation on an archived thread, such as editing a message or adding a user to the thread
	JSONErrorInvalidThreadNotificationSettings                                JSONErrorCode = 50084  // Invalid thread notification settings
	JSONErrorValueIsEarlierThanTheThreadCreationDate                          JSONErrorCode = 50085  //  value is earlier than the thread creation date
	JSONErrorCommunityServerChannelsMustBeTextChannels                        JSONErrorCode = 50086  // Community server channels must be text channels
	JSONErrorThisServerIsNotAvailableInYourLocation                           JSONErrorCode = 50095  // This server is not available in your location
	JSONErrorThisServerNeedsMonetizationEnabledInOrderToPerformThisAction     JSONErrorCode = 50097  // This server needs monetization enabled in order to perform this action
	JSONErrorThisServerNeedsMoreBoostsToPerformThisAction                     JSONErrorCode = 50101  // This server needs more boosts to perform this action
	JSONErrorTheRequestBodyContainsInvalidJSON                                JSONErrorCode = 50109  // The request body contains invalid JSON.
	JSONErrorTwoFactorIsRequiredForThisOperation                              JSONErrorCode = 60003  // Two factor is required for this operation
	JSONErrorNoUsersWithDiscordTagExist                                       JSONErrorCode = 80004  // No users with DiscordTag exist
	JSONErrorReactionWasBlocked                                               JSONErrorCode = 90001  // Reaction was blocked
	JSONErrorAPIResourceIsCurrentlyOverloaded                                 JSONErrorCode = 130000 // API resource is currently overloaded. Try again a little later
	JSONErrorTheStageIsAlreadyOpen                                            JSONErrorCode = 150006 // The Stage is already open
	JSONErrorCannotReplyWithoutPermissionToReadMessageHistory                 JSONErrorCode = 160002 // Cannot reply without permission to read message history
	JSONErrorAThreadHasAlreadyBeenCreatedForThisMessage                       JSONErrorCode = 160004 // A thread has already been created for this message
	JSONErrorThreadIsLocked                                                   JSONErrorCode = 160005 // Thread is locked
	JSONErrorMaximumNumberOfActiveThreadsReached                              JSONErrorCode = 160006 // Maximum number of active threads reached
	JSONErrorMaximumNumberOfActiveAnnouncementThreadsReached                  JSONErrorCode = 160007 // Maximum number of active announcement threads reached
	JSONErrorInvalidJSONForUploadedLottieFile                                 JSONErrorCode = 170001 // Invalid JSON for uploaded Lottie file
	JSONErrorUploadedLottiesCannotContainRasterizedImagesSuchAsPNGOrJPEG      JSONErrorCode = 170002 // Uploaded Lotties cannot contain rasterized images such as PNG or JPEG
	JSONErrorStickerMaximumFramerateExceeded                                  JSONErrorCode = 170003 // Sticker maximum framerate exceeded
	JSONErrorStickerFrameCountExceedsMaximumOf1000Frames                      JSONErrorCode = 170004 // Sticker frame count exceeds maximum of 1000 frames
	JSONErrorLottieAnimationMaximumDimensionsExceeded                         JSONErrorCode = 170005 // Lottie animation maximum dimensions exceeded
	JSONErrorStickerFrameRateIsEitherTooSmallOrTooLarge                       JSONErrorCode = 170006 // Sticker frame rate is either too small or too large
	JSONErrorStickerAnimationDurationExceedsMaximumOf5Seconds                 JSONErrorCode = 170007 // Sticker animation duration exceeds maximum of 5 seconds
	JSONErrorCannotUpdateAFinishedEvent                                       JSONErrorCode = 180000 // Cannot update a finished event
	JSONErrorFailedToCreateStageNeededForStageEvent                           JSONErrorCode = 180002 // Failed to create stage needed for stage event
)

