// Code generated by "stringer -type=VerificationLevel,MessageNotificationsLevel,ExplicitContentFilterLevel,MFALevel,PremiumTierLevel,SystemChannelFlags,GuildNSFWLevel -output guild_string.go"; DO NOT EDIT.

package objects

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VerificationLevelNone-0]
	_ = x[VerificationLevelLow-1]
	_ = x[VerificationLevelMedium-2]
	_ = x[VerificationLevelHigh-3]
	_ = x[VerificationLevelVeryHigh-4]
}

const _VerificationLevel_name = "VerificationLevelNoneVerificationLevelLowVerificationLevelMediumVerificationLevelHighVerificationLevelVeryHigh"

var _VerificationLevel_index = [...]uint8{0, 21, 41, 64, 85, 110}

func (i VerificationLevel) String() string {
	if i >= VerificationLevel(len(_VerificationLevel_index)-1) {
		return "VerificationLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VerificationLevel_name[_VerificationLevel_index[i]:_VerificationLevel_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MessageNotificationsLevelAll-0]
	_ = x[MessageNotificationsLevelOnlyMentions-1]
}

const _MessageNotificationsLevel_name = "MessageNotificationsLevelAllMessageNotificationsLevelOnlyMentions"

var _MessageNotificationsLevel_index = [...]uint8{0, 28, 65}

func (i MessageNotificationsLevel) String() string {
	if i >= MessageNotificationsLevel(len(_MessageNotificationsLevel_index)-1) {
		return "MessageNotificationsLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MessageNotificationsLevel_name[_MessageNotificationsLevel_index[i]:_MessageNotificationsLevel_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExplicitContentFilterLevelDisabled-0]
	_ = x[ExplicitContentFilterLevelMembersWithoutRoles-1]
	_ = x[ExplicitContentFilterLevelAllMembers-2]
}

const _ExplicitContentFilterLevel_name = "ExplicitContentFilterLevelDisabledExplicitContentFilterLevelMembersWithoutRolesExplicitContentFilterLevelAllMembers"

var _ExplicitContentFilterLevel_index = [...]uint8{0, 34, 79, 115}

func (i ExplicitContentFilterLevel) String() string {
	if i >= ExplicitContentFilterLevel(len(_ExplicitContentFilterLevel_index)-1) {
		return "ExplicitContentFilterLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExplicitContentFilterLevel_name[_ExplicitContentFilterLevel_index[i]:_ExplicitContentFilterLevel_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MFALevelNone-0]
	_ = x[MFALevelElevated-1]
}

const _MFALevel_name = "MFALevelNoneMFALevelElevated"

var _MFALevel_index = [...]uint8{0, 12, 28}

func (i MFALevel) String() string {
	if i >= MFALevel(len(_MFALevel_index)-1) {
		return "MFALevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MFALevel_name[_MFALevel_index[i]:_MFALevel_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PremiumTierNone-0]
	_ = x[PremiumTier1-1]
	_ = x[PremiumTier2-2]
	_ = x[PremiumTier3-3]
}

const _PremiumTierLevel_name = "PremiumTierNonePremiumTier1PremiumTier2PremiumTier3"

var _PremiumTierLevel_index = [...]uint8{0, 15, 27, 39, 51}

func (i PremiumTierLevel) String() string {
	if i >= PremiumTierLevel(len(_PremiumTierLevel_index)-1) {
		return "PremiumTierLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PremiumTierLevel_name[_PremiumTierLevel_index[i]:_PremiumTierLevel_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FlagSupressJoinNotifications-1]
	_ = x[FlagSupressPremiumSubscriptions-2]
}

const _SystemChannelFlags_name = "FlagSupressJoinNotificationsFlagSupressPremiumSubscriptions"

var _SystemChannelFlags_index = [...]uint8{0, 28, 59}

func (i SystemChannelFlags) String() string {
	i -= 1
	if i >= SystemChannelFlags(len(_SystemChannelFlags_index)-1) {
		return "SystemChannelFlags(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _SystemChannelFlags_name[_SystemChannelFlags_index[i]:_SystemChannelFlags_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GuildNSFWLevelDefault-0]
	_ = x[GuildNSFWLevelExplicit-1]
	_ = x[GuildNSFWLevelSafe-2]
	_ = x[GuildNSFWLevelAgeRestricted-3]
}

const _GuildNSFWLevel_name = "GuildNSFWLevelDefaultGuildNSFWLevelExplicitGuildNSFWLevelSafeGuildNSFWLevelAgeRestricted"

var _GuildNSFWLevel_index = [...]uint8{0, 21, 43, 61, 88}

func (i GuildNSFWLevel) String() string {
	if i < 0 || i >= GuildNSFWLevel(len(_GuildNSFWLevel_index)-1) {
		return "GuildNSFWLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GuildNSFWLevel_name[_GuildNSFWLevel_index[i]:_GuildNSFWLevel_index[i+1]]
}
