// Code generated by "stringer -type=PrivacyLevel -trimprefix=PrivacyLevel -output stage_string.go"; DO NOT EDIT.

package objects

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PrivacyLevelPublic-1]
	_ = x[PrivacyLevelGuildOnly-2]
}

const _PrivacyLevel_name = "PublicGuildOnly"

var _PrivacyLevel_index = [...]uint8{0, 6, 15}

func (i PrivacyLevel) String() string {
	i -= 1
	if i < 0 || i >= PrivacyLevel(len(_PrivacyLevel_index)-1) {
		return "PrivacyLevel(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _PrivacyLevel_name[_PrivacyLevel_index[i]:_PrivacyLevel_index[i+1]]
}
