// Code generated by "stringer -type=WebhookType -trimprefix=Webhook -output webhook_string.go"; DO NOT EDIT.

package objects

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WebhookIncoming-1]
	_ = x[WebhookChannelFollower-2]
	_ = x[WebhookApplication-3]
}

const _WebhookType_name = "IncomingChannelFollowerApplication"

var _WebhookType_index = [...]uint8{0, 8, 23, 34}

func (i WebhookType) String() string {
	i -= 1
	if i >= WebhookType(len(_WebhookType_index)-1) {
		return "WebhookType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _WebhookType_name[_WebhookType_index[i]:_WebhookType_index[i+1]]
}
