// Code generated by /tmp/go-build3502449397/b001/exe/cmdgen -dir ../examples/echo_router_gen/; DO NOT EDIT.

package main

import (
    "wumpgo.dev/wumpgo/objects"
    "wumpgo.dev/wumpgo/objects/permissions"
)


func (c Echo) Description() string {
    return "Echos the message you type back to you"
}

func (c EchoCaps) Description() string {
    return "Echos the message you type back to you, but in all uppercase"
}

func (c EchoCaps) OptionName(optionName string) map[string]string {
    l := map[string]map[string]string{
        "Message": {
            "en_US": "message",
            "es_MX": "mensaje",
        },
    }

    locales, ok := l[optionName]
    if ok {
        return locales
    }

    return map[string]string{}
}

func (c EchoCaps) DefaultPermissions() permissions.PermissionBit {
    return permissions.ManageRoles
}

func (c Log) Description() string {
    return "Tests a channel argument"
}

func (c MyCommand) CommandName() string {
    return "testcommand"
}

func (c MyCommand) Description() string {
    return "Test base command"
}

func (c MyCommand) NameLocalizations() map[string]string {
    return map[string]string{
        "en_US": "testcommand",
        "es_MX": "commandodepreueba",
    }
}

func (c MyCommand) Type() objects.ApplicationCommandType {
    return objects.CommandTypeChatInput
}