// Code generated by wumpgoctl gen; DO NOT EDIT.

package main

import (
    "wumpgo.dev/wumpgo/objects"
    "wumpgo.dev/wumpgo/objects/permissions"
)

func (c Echo) Description() string {
    return "Echos the message you type back to you"
}

func (c EchoCaps) Description() string {
    return "Echos the message you type back to you"
}

func (c Log) Description() string {
    return "Tests a channel argument"
}

func (c MyCommand) CommandName() string {
    return "testcommand"
}

func (c MyCommand) Description() string {
    return "Test base command"
}

func (c MyCommand) NameLocalizations() map[string]string {
    return map[string]string{
        "en-US": "testcommand",
        "es-MX": "commandodepreueba",
    }
}

func (c MyCommand) Type() objects.ApplicationCommandType {
    return objects.CommandTypeChatInput
}

func (c MyCommand) DefaultPermissions() permissions.PermissionBit {
    return permissions.PermissionBit(268435458)
}