// Code generated by "stringer -type=PermissionBit -trimprefix=PermissionBit -output bits_string.go"; DO NOT EDIT.

package permissions

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CreateInstantInvite-1]
	_ = x[KickMembers-2]
	_ = x[BanMembers-4]
	_ = x[Administrator-8]
	_ = x[ManageChannels-16]
	_ = x[ManageGuild-32]
	_ = x[AddReactions-64]
	_ = x[ViewAuditLog-128]
	_ = x[PrioritySpeaker-256]
	_ = x[Stream-512]
	_ = x[ViewChannel-1024]
	_ = x[SendMessages-2048]
	_ = x[SendTTSMessages-4096]
	_ = x[ManageMessages-8192]
	_ = x[EmbedLinks-16384]
	_ = x[AttachFiles-32768]
	_ = x[ReadMessageHistory-65536]
	_ = x[MentionEveryone-131072]
	_ = x[UseExternalEmojis-262144]
	_ = x[ViewGuildInsights-524288]
	_ = x[Connect-1048576]
	_ = x[Speak-2097152]
	_ = x[MuteMembers-4194304]
	_ = x[DeafenMembers-8388608]
	_ = x[MoveMembers-16777216]
	_ = x[UseVAD-33554432]
	_ = x[ChangeNickname-67108864]
	_ = x[ManageNicknames-134217728]
	_ = x[ManageRoles-268435456]
	_ = x[ManageWebhooks-536870912]
	_ = x[ManageEmojisAndStickers-1073741824]
	_ = x[UseApplicationCommands-2147483648]
	_ = x[RequestToSpeak-4294967296]
	_ = x[ManageEvents-8589934592]
	_ = x[ManageThreads-17179869184]
	_ = x[CreatePublicThreads-34359738368]
	_ = x[CreatePrivateThreads-68719476736]
	_ = x[UseExternalStickers-137438953472]
	_ = x[SendMessagesInThreads-274877906944]
	_ = x[StartEmbeddedActivities-549755813888]
	_ = x[ModerateMembers-1099511627776]
}

const _PermissionBit_name = "CreateInstantInviteKickMembersBanMembersAdministratorManageChannelsManageGuildAddReactionsViewAuditLogPrioritySpeakerStreamViewChannelSendMessagesSendTTSMessagesManageMessagesEmbedLinksAttachFilesReadMessageHistoryMentionEveryoneUseExternalEmojisViewGuildInsightsConnectSpeakMuteMembersDeafenMembersMoveMembersUseVADChangeNicknameManageNicknamesManageRolesManageWebhooksManageEmojisAndStickersUseApplicationCommandsRequestToSpeakManageEventsManageThreadsCreatePublicThreadsCreatePrivateThreadsUseExternalStickersSendMessagesInThreadsStartEmbeddedActivitiesModerateMembers"

var _PermissionBit_map = map[PermissionBit]string{
	1:             _PermissionBit_name[0:19],
	2:             _PermissionBit_name[19:30],
	4:             _PermissionBit_name[30:40],
	8:             _PermissionBit_name[40:53],
	16:            _PermissionBit_name[53:67],
	32:            _PermissionBit_name[67:78],
	64:            _PermissionBit_name[78:90],
	128:           _PermissionBit_name[90:102],
	256:           _PermissionBit_name[102:117],
	512:           _PermissionBit_name[117:123],
	1024:          _PermissionBit_name[123:134],
	2048:          _PermissionBit_name[134:146],
	4096:          _PermissionBit_name[146:161],
	8192:          _PermissionBit_name[161:175],
	16384:         _PermissionBit_name[175:185],
	32768:         _PermissionBit_name[185:196],
	65536:         _PermissionBit_name[196:214],
	131072:        _PermissionBit_name[214:229],
	262144:        _PermissionBit_name[229:246],
	524288:        _PermissionBit_name[246:263],
	1048576:       _PermissionBit_name[263:270],
	2097152:       _PermissionBit_name[270:275],
	4194304:       _PermissionBit_name[275:286],
	8388608:       _PermissionBit_name[286:299],
	16777216:      _PermissionBit_name[299:310],
	33554432:      _PermissionBit_name[310:316],
	67108864:      _PermissionBit_name[316:330],
	134217728:     _PermissionBit_name[330:345],
	268435456:     _PermissionBit_name[345:356],
	536870912:     _PermissionBit_name[356:370],
	1073741824:    _PermissionBit_name[370:393],
	2147483648:    _PermissionBit_name[393:415],
	4294967296:    _PermissionBit_name[415:429],
	8589934592:    _PermissionBit_name[429:441],
	17179869184:   _PermissionBit_name[441:454],
	34359738368:   _PermissionBit_name[454:473],
	68719476736:   _PermissionBit_name[473:493],
	137438953472:  _PermissionBit_name[493:512],
	274877906944:  _PermissionBit_name[512:533],
	549755813888:  _PermissionBit_name[533:556],
	1099511627776: _PermissionBit_name[556:571],
}

func (i PermissionBit) String() string {
	if str, ok := _PermissionBit_map[i]; ok {
		return str
	}
	return "PermissionBit(" + strconv.FormatInt(int64(i), 10) + ")"
}
